### ISSUE TITLE
Error "Script @bcombat\bcombat.sqf not found" when Mod not in Arma3 root folder

### ISSUE THREAD

**Issue by derdeagle** [fabrizioT/bCombat#2]
First of all: great work. We ran a test with your ai and it went great!

Even though one of us received the following error (also described in the subject of this issue).

![bcombat fehler](https://cloud.githubusercontent.com/assets/11424540/8763484/4cd4f87e-2d9e-11e5-9250-3abfd5dba939.png)

We "resolved" this error just by moving the mod folder from another directly into the Arma3 root folder.
The error message then did not show up again.
I verified this by moving my bcombat-mod-folder to a subfolder of the Arma3 root and it was not initialized (hint in the top right hand corner did not show up).

Another thing is that you archived the mod folder with the name "@bCombat-0.18" which leads to another error ingame. If renamed to "@bCombat" it works.

Sincerely,
derdeagle

**Comment by stephanschoem** [comment]
High after the recent update I came across this error. Problem is I normally copy my mods into the arma root ex "Arma3/@bcombat". might be a path thats changed in Arma 3?

**Comment by fabrizioT** [comment]
Mod -should- be installed into  a folder named "@bcombat" within your main Arma3 durectory, e.g. "Arma3/@bcombat". Then please run the game with the "-filepatching" command-line argument.

**Comment by stephanschoem** [comment]
Thanks sorted

-----Original Message-----

**Comment by derdeagle** [comment]
Okay, thank you!
